server:
  port: 7011

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zhaozhikang157/springCloudConfig
          username:
          password:
          search-paths:
      label: master

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/

